parameters:
    crop.controller.class: BackBee\Bundle\CropBundle\Controller\CropController
services:
    crop.controller:
        class: %crop.controller.class%
        arguments: [@bbapp, @bundle.crop.config, @routing]